<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20200720072221 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE hum_aid_item_delivery (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, hum_aid_item_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, delivered_at DATE NOT NULL, sync_id INT DEFAULT NULL, sort INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_203D8F4619EB6921 (client_id), INDEX IDX_203D8F468DBAF256 (hum_aid_item_id), INDEX IDX_203D8F46B03A8386 (created_by_id), INDEX IDX_203D8F46896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hum_aid_item (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, category INT NOT NULL, limit_days INT NOT NULL, sync_id INT DEFAULT NULL, sort INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_461A6508B03A8386 (created_by_id), INDEX IDX_461A6508896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE hum_aid_item_delivery ADD CONSTRAINT FK_203D8F4619EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE hum_aid_item_delivery ADD CONSTRAINT FK_203D8F468DBAF256 FOREIGN KEY (hum_aid_item_id) REFERENCES hum_aid_item (id)');
        $this->addSql('ALTER TABLE hum_aid_item_delivery ADD CONSTRAINT FK_203D8F46B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE hum_aid_item_delivery ADD CONSTRAINT FK_203D8F46896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE hum_aid_item ADD CONSTRAINT FK_461A6508B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE hum_aid_item ADD CONSTRAINT FK_461A6508896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id)');
//        $this->addSql('ALTER TABLE fos_user_user CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE position_id position_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT NULL, CHANGE date_of_birth date_of_birth DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL, CHANGE lastname lastname VARCHAR(64) DEFAULT NULL, CHANGE website website VARCHAR(64) DEFAULT NULL, CHANGE biography biography VARCHAR(1000) DEFAULT NULL, CHANGE gender gender VARCHAR(1) DEFAULT NULL, CHANGE locale locale VARCHAR(8) DEFAULT NULL, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL, CHANGE phone phone VARCHAR(64) DEFAULT NULL, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT NULL, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT NULL, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT NULL, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT NULL, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL, CHANGE proxy_date proxy_date DATE DEFAULT NULL, CHANGE proxy_num proxy_num VARCHAR(255) DEFAULT NULL, CHANGE position_text position_text LONGTEXT DEFAULT NULL');
//        $this->addSql('ALTER TABLE fos_user_group CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL');
//        $this->addSql('ALTER TABLE viewed_client CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE position CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE notice CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_form_response CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE resident_questionnaire_id resident_questionnaire_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE district CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE document_file CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE generated_document_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_field CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE type type INT DEFAULT NULL, CHANGE required required TINYINT(1) DEFAULT NULL, CHANGE multiple multiple TINYINT(1) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE mandatory_for_homeless mandatory_for_homeless TINYINT(1) DEFAULT NULL, CHANGE enabled_for_homeless enabled_for_homeless TINYINT(1) DEFAULT NULL');
//        $this->addSql('ALTER TABLE region CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE generated_document_end_text CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE shelter_room CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE max_occupants max_occupants INT DEFAULT NULL, CHANGE current_occupants current_occupants INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE shelter_history CHANGE client_id client_id INT DEFAULT NULL, CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE room_id room_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE diphtheria_vaccination_date diphtheria_vaccination_date DATE DEFAULT NULL, CHANGE fluorography_date fluorography_date DATE DEFAULT NULL, CHANGE hepatitis_vaccination_date hepatitis_vaccination_date DATE DEFAULT NULL, CHANGE typhus_vaccination_date typhus_vaccination_date DATE DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client CHANGE last_registration_district_id last_registration_district_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE last_residence_district_id last_residence_district_id INT DEFAULT NULL, CHANGE photo_name photo_name VARCHAR(255) DEFAULT NULL, CHANGE birth_date birth_date DATE DEFAULT NULL, CHANGE birth_place birth_place VARCHAR(255) DEFAULT NULL, CHANGE gender gender INT DEFAULT NULL, CHANGE firstname firstname VARCHAR(255) DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE is_homeless is_homeless TINYINT(1) DEFAULT NULL');
//        $this->addSql('ALTER TABLE menu_item CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE note CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE important important TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_form CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE certificate_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE downloadable downloadable TINYINT(1) DEFAULT NULL, CHANGE show_photo show_photo TINYINT(1) DEFAULT NULL, CHANGE show_date show_date TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE certificate CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE resident_questionnaire DROP FOREIGN KEY resident_questionnaire_client_id_fk');
//        $this->addSql('ALTER TABLE resident_questionnaire DROP FOREIGN KEY resident_questionnaire_client_id_fk');
//        $this->addSql('ALTER TABLE resident_questionnaire CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE is_dwelling is_dwelling TINYINT(1) DEFAULT NULL, CHANGE room_type_id room_type_id INT DEFAULT NULL, CHANGE is_work is_work TINYINT(1) DEFAULT NULL, CHANGE is_work_official is_work_official TINYINT(1) DEFAULT NULL, CHANGE is_work_constant is_work_constant TINYINT(1) DEFAULT NULL, CHANGE changed_jobs_count_id changed_jobs_count_id INT DEFAULT NULL, CHANGE reason_for_transition_ids reason_for_transition_ids LONGTEXT DEFAULT NULL, CHANGE reason_for_petition_ids reason_for_petition_ids LONGTEXT DEFAULT NULL');
//        $this->addSql('ALTER TABLE resident_questionnaire ADD CONSTRAINT FK_D177694B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
//        $this->addSql('DROP INDEX resident_questionnaire_client_id_fk ON resident_questionnaire');
//        $this->addSql('CREATE INDEX IDX_D177694B19EB6921 ON resident_questionnaire (client_id)');
//        $this->addSql('ALTER TABLE resident_questionnaire ADD CONSTRAINT resident_questionnaire_client_id_fk FOREIGN KEY (client_id) REFERENCES client (id) ON UPDATE CASCADE ON DELETE CASCADE');
//        $this->addSql('ALTER TABLE shelter_status CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE generated_document_start_text CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('DROP INDEX uniq_d7f214358a90aba9 ON meta');
//        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7F214354E645A7E ON meta (`key`)');
//        $this->addSql('ALTER TABLE client_form_field CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE flags flags LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3443707B0');
//        $this->addSql('ALTER TABLE client_field_option CHANGE field_id field_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE not_single not_single TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3443707B0 FOREIGN KEY (field_id) REFERENCES client_field (id)');
//        $this->addSql('ALTER TABLE contract_item CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE date_start date_start DATE DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE contract_status CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE document CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE number_prefix number_prefix VARCHAR(255) DEFAULT NULL, CHANGE registration registration INT DEFAULT NULL, CHANGE issued issued VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE service_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE pay pay TINYINT(1) DEFAULT NULL, CHANGE document document TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE contract_item_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE generated_document CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE start_text_id start_text_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE end_text_id end_text_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE document_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE type type INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE history CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE contract CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_form_response_value CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE service CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4443707B0');
//        $this->addSql('ALTER TABLE client_field_value CHANGE client_id client_id INT DEFAULT NULL, CHANGE field_id field_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE option_id option_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE datetime datetime DATETIME DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
//        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4443707B0 FOREIGN KEY (field_id) REFERENCES client_field (id)');
//        $this->addSql('ALTER TABLE history_download CHANGE client_id client_id INT DEFAULT NULL, CHANGE certificate_type_id certificate_type_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE hum_aid_item_delivery DROP FOREIGN KEY FK_203D8F468DBAF256');
        $this->addSql('DROP TABLE hum_aid_item_delivery');
        $this->addSql('DROP TABLE hum_aid_item');
//        $this->addSql('ALTER TABLE certificate CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE date_from date_from DATE DEFAULT \'NULL\', CHANGE date_to date_to DATE DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE certificate_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE downloadable downloadable TINYINT(1) DEFAULT \'NULL\', CHANGE show_photo show_photo TINYINT(1) DEFAULT \'NULL\', CHANGE show_date show_date TINYINT(1) DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client CHANGE last_residence_district_id last_residence_district_id INT DEFAULT NULL, CHANGE last_registration_district_id last_registration_district_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE photo_name photo_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE birth_date birth_date DATE DEFAULT \'NULL\', CHANGE birth_place birth_place VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gender gender INT DEFAULT NULL, CHANGE firstname firstname VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE middlename middlename VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE is_homeless is_homeless INT DEFAULT 1 NOT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_field CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE enabled enabled TINYINT(1) DEFAULT \'NULL\', CHANGE enabled_for_homeless enabled_for_homeless TINYINT(1) DEFAULT \'0\', CHANGE type type INT DEFAULT NULL, CHANGE required required TINYINT(1) DEFAULT \'NULL\', CHANGE mandatory_for_homeless mandatory_for_homeless INT DEFAULT 0 NOT NULL, CHANGE multiple multiple TINYINT(1) DEFAULT \'NULL\', CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3443707B0');
//        $this->addSql('ALTER TABLE client_field_option CHANGE field_id field_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE not_single not_single TINYINT(1) DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3443707B0 FOREIGN KEY (field_id) REFERENCES client_field (id) ON DELETE CASCADE');
//        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4443707B0');
//        $this->addSql('ALTER TABLE client_field_value CHANGE field_id field_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE option_id option_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE datetime datetime DATETIME DEFAULT \'NULL\', CHANGE filename filename VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4443707B0 FOREIGN KEY (field_id) REFERENCES client_field (id) ON DELETE CASCADE');
//        $this->addSql('ALTER TABLE client_form CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_form_field CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE flags flags LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:simple_array)\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_form_response CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE resident_questionnaire_id resident_questionnaire_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE client_form_response_value CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE contract CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE date_from date_from DATE DEFAULT \'NULL\', CHANGE date_to date_to DATE DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE contract_item CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE date_start date_start DATE DEFAULT \'NULL\', CHANGE date date DATE DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE contract_item_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE short_name short_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE contract_status CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE district CHANGE region_id region_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE document CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE date date DATE DEFAULT \'NULL\', CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE number_prefix number_prefix VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE registration registration INT DEFAULT NULL, CHANGE issued issued VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE document_file CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE document_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE type type INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE fos_user_group CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
//        $this->addSql('ALTER TABLE fos_user_user CHANGE position_id position_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE expires_at expires_at DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT \'NULL\', CHANGE date_of_birth date_of_birth DATETIME DEFAULT \'NULL\', CHANGE firstname firstname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE website website VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE biography biography VARCHAR(1000) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gender gender VARCHAR(1) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE locale locale VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE timezone timezone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_data facebook_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE twitter_data twitter_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gplus_data gplus_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE proxy_date proxy_date DATE DEFAULT \'NULL\', CHANGE proxy_num proxy_num VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE position_text position_text VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
//        $this->addSql('ALTER TABLE generated_document CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE start_text_id start_text_id INT DEFAULT NULL, CHANGE end_text_id end_text_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE generated_document_end_text CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE generated_document_start_text CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE generated_document_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE history CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE history_download CHANGE client_id client_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE certificate_type_id certificate_type_id INT DEFAULT NULL');
//        $this->addSql('ALTER TABLE menu_item CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE enabled enabled TINYINT(1) DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('DROP INDEX uniq_d7f214354e645a7e ON meta');
//        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7F214358A90ABA9 ON meta (`key`)');
//        $this->addSql('ALTER TABLE note CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE important important TINYINT(1) DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE notice CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE date date DATE DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE position CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE region CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE short_name short_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE resident_questionnaire DROP FOREIGN KEY FK_D177694B19EB6921');
//        $this->addSql('ALTER TABLE resident_questionnaire DROP FOREIGN KEY FK_D177694B19EB6921');
//        $this->addSql('ALTER TABLE resident_questionnaire CHANGE client_id client_id INT NOT NULL, CHANGE type_id type_id INT NOT NULL, CHANGE is_dwelling is_dwelling INT DEFAULT NULL, CHANGE room_type_id room_type_id INT DEFAULT NULL, CHANGE is_work is_work INT DEFAULT NULL, CHANGE is_work_official is_work_official INT DEFAULT NULL, CHANGE is_work_constant is_work_constant INT DEFAULT NULL, CHANGE changed_jobs_count_id changed_jobs_count_id INT DEFAULT NULL, CHANGE reason_for_transition_ids reason_for_transition_ids VARCHAR(64) DEFAULT \'NULL\' COLLATE latin1_swedish_ci, CHANGE reason_for_petition_ids reason_for_petition_ids VARCHAR(64) DEFAULT \'NULL\' COLLATE latin1_swedish_ci');
//        $this->addSql('ALTER TABLE resident_questionnaire ADD CONSTRAINT resident_questionnaire_client_id_fk FOREIGN KEY (client_id) REFERENCES client (id) ON UPDATE CASCADE ON DELETE CASCADE');
//        $this->addSql('DROP INDEX idx_d177694b19eb6921 ON resident_questionnaire');
//        $this->addSql('CREATE INDEX resident_questionnaire_client_id_fk ON resident_questionnaire (client_id)');
//        $this->addSql('ALTER TABLE resident_questionnaire ADD CONSTRAINT FK_D177694B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
//        $this->addSql('ALTER TABLE service CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE service_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE pay pay TINYINT(1) DEFAULT \'NULL\', CHANGE document document TINYINT(1) DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE shelter_history CHANGE room_id room_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE diphtheria_vaccination_date diphtheria_vaccination_date DATE DEFAULT \'NULL\', CHANGE fluorography_date fluorography_date DATE DEFAULT \'NULL\', CHANGE hepatitis_vaccination_date hepatitis_vaccination_date DATE DEFAULT \'NULL\', CHANGE typhus_vaccination_date typhus_vaccination_date DATE DEFAULT \'NULL\', CHANGE date_from date_from DATE DEFAULT \'NULL\', CHANGE date_to date_to DATE DEFAULT \'NULL\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE shelter_room CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE max_occupants max_occupants INT DEFAULT NULL, CHANGE current_occupants current_occupants INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE shelter_status CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
//        $this->addSql('ALTER TABLE viewed_client CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
    }
}
