app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: admin.yml

api:
    type: rest
    prefix: api/v1
    resource: "@AppBundle/Controller/API/ClientsController.php"



fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

